### ISSUE TITLE
Update available, but it is right updated? Error on Verioncheck?

### ISSUE THREAD

**Issue by suerion** [syorito-hatsuki/ducky-updater-rework#1]
Hey, i think, the Screenshot says all, all Mods what are listed, are updated, the most updates from Modrinth.

![grafik](https://github.com/syorito-hatsuki/ducky-updater/assets/55131959/49e4351b-46b4-4ec0-8d2b-dcd07da703a5)

**Comment by syorito-hatsuki** [comment]
That is an unknown problem with Modrinth API. For check updates, I send jar file hash to Modrinth and it on the backend checks needs or does not need an update. And ye. Sometimes happen that. Also, it may be the mods dev's issue, because the naming versions diff in Minecraft and on the Modrinth site. That's why I added the `ignore` command :)

**Comment by syorito-hatsuki** [comment]
Fixed in https://github.com/syorito-hatsuki/ducky-updater-rework/pull/10, soon will be uploaded to Modrinth and CurseForge
